Revert "prune __init__"
This reverts commit bbafec91357abf42de11553d8a513279d04f508e.
Otherwise MultiEncoder cant be imported(?!)

 python -c "from nupic.encoders import MultiEncoder"
Traceback (most recent call last):
File "", line 1, in
ImportError: cannot import name MultiEncoder